"""Initial PostgreSQL schema

Revision ID: 7e048d0d762b
Revises: 
Create Date: 2026-09-06 16:21:55.176518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e048d0d762b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_ledger_blocks',
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('data_payload', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('block_index')
    )
    op.create_index(op.f('ix_blockchain_ledger_blocks_block_index'), 'blockchain_ledger_blocks', ['block_index'], unique=False)
    op.create_table('district_soil_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('taluk_block', sa.String(length=50), nullable=False),
    sa.Column('village_panchayath', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=False),
    sa.Column('electrical_conductivity_ec', sa.Float(), nullable=True),
    sa.Column('organic_carbon_percent', sa.Float(), nullable=True),
    sa.Column('nitrogen_kg_per_hectare', sa.Float(), nullable=True),
    sa.Column('phosphorus_kg_per_hectare', sa.Float(), nullable=True),
    sa.Column('potassium_kg_per_hectare', sa.Float(), nullable=True),
    sa.Column('surveyor_name', sa.String(length=100), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_soil_surveys_district'), 'district_soil_surveys', ['district'], unique=False)
    op.create_index(op.f('ix_district_soil_surveys_id'), 'district_soil_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_district_soil_surveys_state'), 'district_soil_surveys', ['state'], unique=False)
    op.create_index(op.f('ix_district_soil_surveys_taluk_block'), 'district_soil_surveys', ['taluk_block'], unique=False)
    op.create_table('electricity_tariff_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('consumer_category', sa.String(length=50), nullable=False),
    sa.Column('rate_per_unit_inr', sa.Float(), nullable=False),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricity_tariff_index_id'), 'electricity_tariff_index', ['id'], unique=False)
    op.create_index(op.f('ix_electricity_tariff_index_state'), 'electricity_tariff_index', ['state'], unique=False)
    op.create_table('feed_price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=False),
    sa.Column('feed_name', sa.String(length=50), nullable=False),
    sa.Column('official_price_per_kg', sa.Float(), nullable=False),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_price_index_id'), 'feed_price_index', ['id'], unique=False)
    op.create_index(op.f('ix_feed_price_index_state'), 'feed_price_index', ['state'], unique=False)
    op.create_table('fertilizer_price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fertilizer_type', sa.String(length=50), nullable=False),
    sa.Column('bag_weight_kg', sa.Float(), nullable=False),
    sa.Column('official_mrp_per_bag', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('state_subsidy_offset', sa.Float(), nullable=False),
    sa.Column('effective_price_per_bag', sa.Float(), nullable=False),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fertilizer_price_index_id'), 'fertilizer_price_index', ['id'], unique=False)
    op.create_table('fuel_price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('diesel_rate_per_liter', sa.Float(), nullable=False),
    sa.Column('petrol_rate_per_liter', sa.Float(), nullable=False),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_price_index_district'), 'fuel_price_index', ['district'], unique=False)
    op.create_index(op.f('ix_fuel_price_index_id'), 'fuel_price_index', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_price_index_state'), 'fuel_price_index', ['state'], unique=False)
    op.create_table('geo_region_language_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('regional_language_code', sa.String(length=10), nullable=False),
    sa.Column('dialect_pack_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_region_language_maps_district'), 'geo_region_language_maps', ['district'], unique=False)
    op.create_index(op.f('ix_geo_region_language_maps_id'), 'geo_region_language_maps', ['id'], unique=False)
    op.create_table('historical_climate_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('avg_rainfall_mm_20yr', sa.Float(), nullable=False),
    sa.Column('avg_temp_min_c', sa.Float(), nullable=False),
    sa.Column('avg_temp_max_c', sa.Float(), nullable=False),
    sa.Column('drought_risk_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_climate_data_district'), 'historical_climate_data', ['district'], unique=False)
    op.create_index(op.f('ix_historical_climate_data_id'), 'historical_climate_data', ['id'], unique=False)
    op.create_table('labour_rate_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('labour_type', sa.String(length=50), nullable=False),
    sa.Column('rate_per_day_inr', sa.Float(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_rate_index_district'), 'labour_rate_index', ['district'], unique=False)
    op.create_index(op.f('ix_labour_rate_index_id'), 'labour_rate_index', ['id'], unique=False)
    op.create_index(op.f('ix_labour_rate_index_state'), 'labour_rate_index', ['state'], unique=False)
    op.create_table('market_price_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_name', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('mandi_name', sa.String(length=100), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('price_unit', sa.String(length=20), nullable=False),
    sa.Column('official_source', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_trends_commodity_name'), 'market_price_trends', ['commodity_name'], unique=False)
    op.create_index(op.f('ix_market_price_trends_district'), 'market_price_trends', ['district'], unique=False)
    op.create_index(op.f('ix_market_price_trends_id'), 'market_price_trends', ['id'], unique=False)
    op.create_index(op.f('ix_market_price_trends_state'), 'market_price_trends', ['state'], unique=False)
    op.create_table('official_fertilizer_mrp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('fertilizer_name', sa.String(length=100), nullable=False),
    sa.Column('official_mrp_inr', sa.Float(), nullable=False),
    sa.Column('merkle_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_code_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_fertilizer_mrp_batch_number'), 'official_fertilizer_mrp', ['batch_number'], unique=True)
    op.create_index(op.f('ix_official_fertilizer_mrp_id'), 'official_fertilizer_mrp', ['id'], unique=False)
    op.create_table('otp_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_id'), 'otp_records', ['id'], unique=False)
    op.create_index(op.f('ix_otp_records_phone_number'), 'otp_records', ['phone_number'], unique=False)
    op.create_table('suggestion_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('advisory_recommendation', sa.Text(), nullable=False),
    sa.Column('verifier_audit_passed', sa.Boolean(), nullable=False),
    sa.Column('verifier_feedback', sa.Text(), nullable=True),
    sa.Column('spoken_audio_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_audit_logs_id'), 'suggestion_audit_logs', ['id'], unique=False)
    op.create_table('transport_cost_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_district', sa.String(length=50), nullable=False),
    sa.Column('to_mandi', sa.String(length=100), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_cost_per_quintal_inr', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_cost_index_from_district'), 'transport_cost_index', ['from_district'], unique=False)
    op.create_index(op.f('ix_transport_cost_index_id'), 'transport_cost_index', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('verified_produce_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produce_batch_id', sa.String(length=50), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('produce_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('merkle_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_code_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_produce_stock_id'), 'verified_produce_stock', ['id'], unique=False)
    op.create_index(op.f('ix_verified_produce_stock_produce_batch_id'), 'verified_produce_stock', ['produce_batch_id'], unique=True)
    op.create_table('veterinary_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=100), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('sub_district', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinary_services_district'), 'veterinary_services', ['district'], unique=False)
    op.create_index(op.f('ix_veterinary_services_id'), 'veterinary_services', ['id'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('sub_district', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('voice_preference', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmer_profiles_id'), 'farmer_profiles', ['id'], unique=False)
    op.create_table('agricultural_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('plot_name', sa.String(length=50), nullable=False),
    sa.Column('acreage', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.Column('water_source', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultural_plots_id'), 'agricultural_plots', ['id'], unique=False)
    op.create_table('aquaculture_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('pond_name', sa.String(length=50), nullable=False),
    sa.Column('pond_size_acres', sa.Float(), nullable=False),
    sa.Column('fish_species', sa.String(length=100), nullable=False),
    sa.Column('water_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aquaculture_units_id'), 'aquaculture_units', ['id'], unique=False)
    op.create_table('livestock_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_units_id'), 'livestock_units', ['id'], unique=False)
    op.create_table('poultry_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('bird_type', sa.String(length=50), nullable=False),
    sa.Column('bird_count', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_units_id'), 'poultry_units', ['id'], unique=False)
    op.create_table('aquaculture_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('fish_harvest_kg', sa.Float(), nullable=False),
    sa.Column('sale_price_per_kg', sa.Float(), nullable=True),
    sa.Column('feed_cost_cycle', sa.Float(), nullable=False),
    sa.Column('verification_tier', sa.Enum('PLATFORM_VERIFIED', 'SELF_REPORTED', name='verificationtier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['aquaculture_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aquaculture_records_id'), 'aquaculture_records', ['id'], unique=False)
    op.create_table('crop_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('quantity_produced', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('sale_price_per_unit', sa.Float(), nullable=True),
    sa.Column('input_cost_total', sa.Float(), nullable=False),
    sa.Column('verification_tier', sa.Enum('PLATFORM_VERIFIED', 'SELF_REPORTED', name='verificationtier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['agricultural_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_records_id'), 'crop_records', ['id'], unique=False)
    op.create_table('farmer_soil_health_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('shc_number', sa.String(length=50), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=False),
    sa.Column('organic_carbon_percent', sa.Float(), nullable=True),
    sa.Column('nitrogen_status', sa.String(length=20), nullable=False),
    sa.Column('phosphorus_status', sa.String(length=20), nullable=False),
    sa.Column('potassium_status', sa.String(length=20), nullable=False),
    sa.Column('testing_lab_name', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['agricultural_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_soil_health_cards_id'), 'farmer_soil_health_cards', ['id'], unique=False)
    op.create_table('livestock_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('daily_yield_liters', sa.Float(), nullable=True),
    sa.Column('sale_price_per_liter', sa.Float(), nullable=True),
    sa.Column('feed_cost_monthly', sa.Float(), nullable=False),
    sa.Column('verification_tier', sa.Enum('PLATFORM_VERIFIED', 'SELF_REPORTED', name='verificationtier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['livestock_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_records_id'), 'livestock_records', ['id'], unique=False)
    op.create_table('poultry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('daily_egg_count', sa.Integer(), nullable=True),
    sa.Column('sale_price_per_egg', sa.Float(), nullable=True),
    sa.Column('feed_cost_monthly', sa.Float(), nullable=False),
    sa.Column('verification_tier', sa.Enum('PLATFORM_VERIFIED', 'SELF_REPORTED', name='verificationtier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['poultry_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_records_id'), 'poultry_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poultry_records_id'), table_name='poultry_records')
    op.drop_table('poultry_records')
    op.drop_index(op.f('ix_livestock_records_id'), table_name='livestock_records')
    op.drop_table('livestock_records')
    op.drop_index(op.f('ix_farmer_soil_health_cards_id'), table_name='farmer_soil_health_cards')
    op.drop_table('farmer_soil_health_cards')
    op.drop_index(op.f('ix_crop_records_id'), table_name='crop_records')
    op.drop_table('crop_records')
    op.drop_index(op.f('ix_aquaculture_records_id'), table_name='aquaculture_records')
    op.drop_table('aquaculture_records')
    op.drop_index(op.f('ix_poultry_units_id'), table_name='poultry_units')
    op.drop_table('poultry_units')
    op.drop_index(op.f('ix_livestock_units_id'), table_name='livestock_units')
    op.drop_table('livestock_units')
    op.drop_index(op.f('ix_aquaculture_units_id'), table_name='aquaculture_units')
    op.drop_table('aquaculture_units')
    op.drop_index(op.f('ix_agricultural_plots_id'), table_name='agricultural_plots')
    op.drop_table('agricultural_plots')
    op.drop_index(op.f('ix_farmer_profiles_id'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_veterinary_services_id'), table_name='veterinary_services')
    op.drop_index(op.f('ix_veterinary_services_district'), table_name='veterinary_services')
    op.drop_table('veterinary_services')
    op.drop_index(op.f('ix_verified_produce_stock_produce_batch_id'), table_name='verified_produce_stock')
    op.drop_index(op.f('ix_verified_produce_stock_id'), table_name='verified_produce_stock')
    op.drop_table('verified_produce_stock')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transport_cost_index_id'), table_name='transport_cost_index')
    op.drop_index(op.f('ix_transport_cost_index_from_district'), table_name='transport_cost_index')
    op.drop_table('transport_cost_index')
    op.drop_index(op.f('ix_suggestion_audit_logs_id'), table_name='suggestion_audit_logs')
    op.drop_table('suggestion_audit_logs')
    op.drop_index(op.f('ix_otp_records_phone_number'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_id'), table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_index(op.f('ix_official_fertilizer_mrp_id'), table_name='official_fertilizer_mrp')
    op.drop_index(op.f('ix_official_fertilizer_mrp_batch_number'), table_name='official_fertilizer_mrp')
    op.drop_table('official_fertilizer_mrp')
    op.drop_index(op.f('ix_market_price_trends_state'), table_name='market_price_trends')
    op.drop_index(op.f('ix_market_price_trends_id'), table_name='market_price_trends')
    op.drop_index(op.f('ix_market_price_trends_district'), table_name='market_price_trends')
    op.drop_index(op.f('ix_market_price_trends_commodity_name'), table_name='market_price_trends')
    op.drop_table('market_price_trends')
    op.drop_index(op.f('ix_labour_rate_index_state'), table_name='labour_rate_index')
    op.drop_index(op.f('ix_labour_rate_index_id'), table_name='labour_rate_index')
    op.drop_index(op.f('ix_labour_rate_index_district'), table_name='labour_rate_index')
    op.drop_table('labour_rate_index')
    op.drop_index(op.f('ix_historical_climate_data_id'), table_name='historical_climate_data')
    op.drop_index(op.f('ix_historical_climate_data_district'), table_name='historical_climate_data')
    op.drop_table('historical_climate_data')
    op.drop_index(op.f('ix_geo_region_language_maps_id'), table_name='geo_region_language_maps')
    op.drop_index(op.f('ix_geo_region_language_maps_district'), table_name='geo_region_language_maps')
    op.drop_table('geo_region_language_maps')
    op.drop_index(op.f('ix_fuel_price_index_state'), table_name='fuel_price_index')
    op.drop_index(op.f('ix_fuel_price_index_id'), table_name='fuel_price_index')
    op.drop_index(op.f('ix_fuel_price_index_district'), table_name='fuel_price_index')
    op.drop_table('fuel_price_index')
    op.drop_index(op.f('ix_fertilizer_price_index_id'), table_name='fertilizer_price_index')
    op.drop_table('fertilizer_price_index')
    op.drop_index(op.f('ix_feed_price_index_state'), table_name='feed_price_index')
    op.drop_index(op.f('ix_feed_price_index_id'), table_name='feed_price_index')
    op.drop_table('feed_price_index')
    op.drop_index(op.f('ix_electricity_tariff_index_state'), table_name='electricity_tariff_index')
    op.drop_index(op.f('ix_electricity_tariff_index_id'), table_name='electricity_tariff_index')
    op.drop_table('electricity_tariff_index')
    op.drop_index(op.f('ix_district_soil_surveys_taluk_block'), table_name='district_soil_surveys')
    op.drop_index(op.f('ix_district_soil_surveys_state'), table_name='district_soil_surveys')
    op.drop_index(op.f('ix_district_soil_surveys_id'), table_name='district_soil_surveys')
    op.drop_index(op.f('ix_district_soil_surveys_district'), table_name='district_soil_surveys')
    op.drop_table('district_soil_surveys')
    op.drop_index(op.f('ix_blockchain_ledger_blocks_block_index'), table_name='blockchain_ledger_blocks')
    op.drop_table('blockchain_ledger_blocks')
    # ### end Alembic commands ###
